### ISSUE TITLE
cannot import name 'prepare_result_dir'

### ISSUE THREAD

**Issue by Amazingfanta** [hengliusky/UltraSound_SSSR#1]
from utils import prepare_result_dir❌ 
ImportError: cannot import name 'prepare_result_dir'
i can not find prepare_result_dir

**Comment by hengliusky** [comment]
> from utils import prepare_result_dirx
> ImportError: cannot import name 'prepare_result_dir'
> i can not find prepare_result_dir

I have modified some errors in the code and it can now run normally

**Comment by 1632325673** [comment]
作者你好，我出现的这个错误是数据集的问题吗 
 raise ValueError("the number of data points must exceed order + 2 "
ValueError: the number of data points must exceed order + 2 for Bayesian estimate the covariance matrix
