### ISSUE TITLE
ValueError: the number of data points must exceed order + 2 for Bayesian estimate the covariance matrix

### ISSUE THREAD

**Issue by 1632325673** [hengliusky/UltraSound_SSSR#2]
作者你好，我出现的这个错误是数据集的问题吗
raise ValueError("the number of data points must exceed order + 2 "
ValueError: the number of data points must exceed order + 2 for Bayesian estimate the covariance matrix

**Comment by hidonsea** [comment]
> 作者你好，我出现的这个错误是数据集的问题吗
> raise ValueError("the number of data points must exceed order + 2 "
> ValueError: the number of data points must exceed order + 2 for Bayesian estimate the covariance matrix

你好，我在训练时没有遇到这样的错误。我在训练的时候只要把待超分辨的’.png‘图片放入到config.py中’input_path'这个属性中设置的文件夹下，,然后输入命令就可以正常运行了。刚刚我又重新测试了下，这样是可以正确运行的。

**Comment by 1632325673** [comment]
我把数据集换成jpg格式得到刚刚的错误，换回png格式的话是直接读不到数据
 ValueError: invalid PNG header





------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年8月20日(星期五) 中午11:21
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [hengliusky/UltraSound_SSSR] ValueError: the number of data points must exceed order + 2 for Bayesian estimate the covariance matrix (#2)





  
作者你好，我出现的这个错误是数据集的问题吗
 raise ValueError("the number of data points must exceed order + 2 "
 ValueError: the number of data points must exceed order + 2 for Bayesian estimate the covariance matrix
  
你好，我在训练时没有遇到这样的错误。我在训练的时候只要把待超分辨的’.png‘图片放入到config.py中’input_path'这个属性中设置的文件夹下，,然后输入命令就可以正常运行了。刚刚我又重新测试了下，这样是可以正确运行的。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by hidonsea** [comment]
> 我把数据集换成jpg格式得到刚刚的错误，换回png格式的话是直接读不到数据 ValueError: invalid PNG header
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2021年8月20日(星期五) 中午11:21 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [hengliusky/UltraSound_SSSR] ValueError: the number of data points must exceed order + 2 for Bayesian estimate the covariance matrix (#2) 作者你好，我出现的这个错误是数据集的问题吗 raise ValueError("the number of data points must exceed order + 2 " ValueError: the number of data points must exceed order + 2 for Bayesian estimate the covariance matrix 你好，我在训练时没有遇到这样的错误。我在训练的时候只要把待超分辨的’.png‘图片放入到config.py中’input_path'这个属性中设置的文件夹下，,然后输入命令就可以正常运行了。刚刚我又重新测试了下，这样是可以正确运行的。 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

'ValueError: invalid PNG header'，出现这个错误可能是PNG格式图片通过jpg格式图片直接修改后缀得来的。还有，你的训练环境可能和我的不一样。我的训练环境是：pytorch1.5.0，  python3.8.3， matplotlib3.2.2， 你参考下。

**Comment by 1632325673** [comment]
论文中所给的数据集下载下来就是jpg格式的，如果不用通过改后缀名的方式得到png格式，那请问作者你是怎么转换为png格式的呢



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年8月20日(星期五) 下午3:15
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [hengliusky/UltraSound_SSSR] ValueError: the number of data points must exceed order + 2 for Bayesian estimate the covariance matrix (#2)





  
我把数据集换成jpg格式得到刚刚的错误，换回png格式的话是直接读不到数据 ValueError: invalid PNG header
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: @.&gt;; 发送时间: 2021年8月20日(星期五) 中午11:21 收件人: @.&gt;; 抄送: @.&gt;; @.&gt;; 主题: Re: [hengliusky/UltraSound_SSSR] ValueError: the number of data points must exceed order + 2 for Bayesian estimate the covariance matrix (#2) 作者你好，我出现的这个错误是数据集的问题吗 raise ValueError("the number of data points must exceed order + 2 " ValueError: the number of data points must exceed order + 2 for Bayesian estimate the covariance matrix 你好，我在训练时没有遇到这样的错误。我在训练的时候只要把待超分辨的’.png‘图片放入到config.py中’input_path'这个属性中设置的文件夹下，,然后输入命令就可以正常运行了。刚刚我又重新测试了下，这样是可以正确运行的。 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.
  
'ValueError: invalid PNG header'，出现这个错误可能是PNG格式图片通过jpg格式图片直接修改后缀得来的。还有，你的训练环境可能和我的不一样。我的训练环境是：pytorch1.5.0，  python3.8.3， matplotlib3.2.2， 你参考下。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by hidonsea** [comment]
> 论文中所给的数据集下载下来就是jpg格式的，如果不用通过改后缀名的方式得到png格式，那请问作者你是怎么转换为png格式的呢
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2021年8月20日(星期五) 下午3:15 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [hengliusky/UltraSound_SSSR] ValueError: the number of data points must exceed order + 2 for Bayesian estimate the covariance matrix (#2) 我把数据集换成jpg格式得到刚刚的错误，换回png格式的话是直接读不到数据 ValueError: invalid PNG header … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: @.&gt;; 发送时间: 2021年8月20日(星期五) 中午11:21 收件人: @.&gt;; 抄送: @.&gt;; @.&gt;; 主题: Re: [hengliusky/UltraSound_SSSR] ValueError: the number of data points must exceed order + 2 for Bayesian estimate the covariance matrix (#2) 作者你好，我出现的这个错误是数据集的问题吗 raise ValueError("the number of data points must exceed order + 2 " ValueError: the number of data points must exceed order + 2 for Bayesian estimate the covariance matrix 你好，我在训练时没有遇到这样的错误。我在训练的时候只要把待超分辨的’.png‘图片放入到config.py中’input_path'这个属性中设置的文件夹下，,然后输入命令就可以正常运行了。刚刚我又重新测试了下，这样是可以正确运行的。 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. 'ValueError: invalid PNG header'，出现这个错误可能是PNG格式图片通过jpg格式图片直接修改后缀得来的。还有，你的训练环境可能和我的不一样。我的训练环境是：pytorch1.5.0， python3.8.3， matplotlib3.2.2， 你参考下。 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

你在matlab中，运行下面代码：
`clear;close all;

folder = './';
scale = 4;

%% generate data
filepaths = dir(fullfile(folder,'*.jpg'));
for i = 1 : length(filepaths)
    image = imread(fullfile(folder,filepaths(i).name));
    im_label = modcrop(image, scale);
    im_lr= imresize(im_label, 1/scale, 'bicubic');
    imwrite(im_lr, ['./lr/', num2str(i), '.png'])
    imwrite(im_label,['./label/', num2str(i), '.png']);
end

function imgs = modcrop(imgs, modulo)
if size(imgs,3)==1
    sz = size(imgs);
    sz = sz - mod(sz, modulo);
    imgs = imgs(1:sz(1), 1:sz(2));
else
    tmpsz = size(imgs);
    sz = tmpsz(1:2);
    sz = sz - mod(sz, modulo);
    imgs = imgs(1:sz(1), 1:sz(2),:);
end
end`
这个代码就能得到lr图片和对应的hr图片，格式都是PNG的，可以直接用训练。运行的时候确保路径是正确的。

**Comment by 1632325673** [comment]
可以用啦，谢谢作者百忙中抽空回复，祝一切顺利呀




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年8月21日(星期六) 中午11:54
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [hengliusky/UltraSound_SSSR] ValueError: the number of data points must exceed order + 2 for Bayesian estimate the covariance matrix (#2)





  
论文中所给的数据集下载下来就是jpg格式的，如果不用通过改后缀名的方式得到png格式，那请问作者你是怎么转换为png格式的呢
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: @.&gt;; 发送时间: 2021年8月20日(星期五) 下午3:15 收件人: @.&gt;; 抄送: @.&gt;; @.&gt;; 主题: Re: [hengliusky/UltraSound_SSSR] ValueError: the number of data points must exceed order + 2 for Bayesian estimate the covariance matrix (#2) 我把数据集换成jpg格式得到刚刚的错误，换回png格式的话是直接读不到数据 ValueError: invalid PNG header … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: @.&gt;; 发送时间: 2021年8月20日(星期五) 中午11:21 收件人: @.&gt;; 抄送: @.&gt;; @.&gt;; 主题: Re: [hengliusky/UltraSound_SSSR] ValueError: the number of data points must exceed order + 2 for Bayesian estimate the covariance matrix (#2) 作者你好，我出现的这个错误是数据集的问题吗 raise ValueError("the number of data points must exceed order + 2 " ValueError: the number of data points must exceed order + 2 for Bayesian estimate the covariance matrix 你好，我在训练时没有遇到这样的错误。我在训练的时候只要把待超分辨的’.png‘图片放入到config.py中’input_path'这个属性中设置的文件夹下，,然后输入命令就可以正常运行了。刚刚我又重新测试了下，这样是可以正确运行的。 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. 'ValueError: invalid PNG header'，出现这个错误可能是PNG格式图片通过jpg格式图片直接修改后缀得来的。还有，你的训练环境可能和我的不一样。我的训练环境是：pytorch1.5.0， python3.8.3， matplotlib3.2.2， 你参考下。 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.
  
你在matlab中，运行下面代码：
 `clear;close all;
 
folder = './';
 scale = 4;
 
%% generate data
 filepaths = dir(fullfile(folder,'*.jpg'));
 for i = 1 : length(filepaths)
 image = imread(fullfile(folder,filepaths(i).name));
 im_label = modcrop(image, scale);
 im_lr= imresize(im_label, 1/scale, 'bicubic');
 imwrite(im_lr, ['./lr/', num2str(i), '.png'])
 imwrite(im_label,['./label/', num2str(i), '.png']);
 end
 
function imgs = modcrop(imgs, modulo)
 if size(imgs,3)==1
 sz = size(imgs);
 sz = sz - mod(sz, modulo);
 imgs = imgs(1:sz(1), 1:sz(2));
 else
 tmpsz = size(imgs);
 sz = tmpsz(1:2);
 sz = sz - mod(sz, modulo);
 imgs = imgs(1:sz(1), 1:sz(2),:);
 end
 end`
 这个代码就能得到lr图片和对应的hr图片，格式都是PNG的，可以直接用训练。运行的时候确保路径是正确的。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by 1632325673** [comment]
作者你好，PSNR和SSIM的计算是要自己引入的吗？






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hengliusky/UltraSound_SSSR"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月21日(星期六) 中午11:54
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [hengliusky/UltraSound_SSSR] ValueError: the number of data points must exceed order + 2 for Bayesian estimate the covariance matrix (#2)





  
论文中所给的数据集下载下来就是jpg格式的，如果不用通过改后缀名的方式得到png格式，那请问作者你是怎么转换为png格式的呢
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: @.&gt;; 发送时间: 2021年8月20日(星期五) 下午3:15 收件人: @.&gt;; 抄送: @.&gt;; @.&gt;; 主题: Re: [hengliusky/UltraSound_SSSR] ValueError: the number of data points must exceed order + 2 for Bayesian estimate the covariance matrix (#2) 我把数据集换成jpg格式得到刚刚的错误，换回png格式的话是直接读不到数据 ValueError: invalid PNG header … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: @.&gt;; 发送时间: 2021年8月20日(星期五) 中午11:21 收件人: @.&gt;; 抄送: @.&gt;; @.&gt;; 主题: Re: [hengliusky/UltraSound_SSSR] ValueError: the number of data points must exceed order + 2 for Bayesian estimate the covariance matrix (#2) 作者你好，我出现的这个错误是数据集的问题吗 raise ValueError("the number of data points must exceed order + 2 " ValueError: the number of data points must exceed order + 2 for Bayesian estimate the covariance matrix 你好，我在训练时没有遇到这样的错误。我在训练的时候只要把待超分辨的’.png‘图片放入到config.py中’input_path'这个属性中设置的文件夹下，,然后输入命令就可以正常运行了。刚刚我又重新测试了下，这样是可以正确运行的。 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. 'ValueError: invalid PNG header'，出现这个错误可能是PNG格式图片通过jpg格式图片直接修改后缀得来的。还有，你的训练环境可能和我的不一样。我的训练环境是：pytorch1.5.0， python3.8.3， matplotlib3.2.2， 你参考下。 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.
  
你在matlab中，运行下面代码：
 `clear;close all;
 
folder = './';
 scale = 4;
 
%% generate data
 filepaths = dir(fullfile(folder,'*.jpg'));
 for i = 1 : length(filepaths)
 image = imread(fullfile(folder,filepaths(i).name));
 im_label = modcrop(image, scale);
 im_lr= imresize(im_label, 1/scale, 'bicubic');
 imwrite(im_lr, ['./lr/', num2str(i), '.png'])
 imwrite(im_label,['./label/', num2str(i), '.png']);
 end
 
function imgs = modcrop(imgs, modulo)
 if size(imgs,3)==1
 sz = size(imgs);
 sz = sz - mod(sz, modulo);
 imgs = imgs(1:sz(1), 1:sz(2));
 else
 tmpsz = size(imgs);
 sz = tmpsz(1:2);
 sz = sz - mod(sz, modulo);
 imgs = imgs(1:sz(1), 1:sz(2),:);
 end
 end`
 这个代码就能得到lr图片和对应的hr图片，格式都是PNG的，可以直接用训练。运行的时候确保路径是正确的。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by 1632325673** [comment]
作者你好，可以提供以下US-CASE数据集吗？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hengliusky/UltraSound_SSSR"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月21日(星期六) 中午11:54
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [hengliusky/UltraSound_SSSR] ValueError: the number of data points must exceed order + 2 for Bayesian estimate the covariance matrix (#2)





  
论文中所给的数据集下载下来就是jpg格式的，如果不用通过改后缀名的方式得到png格式，那请问作者你是怎么转换为png格式的呢
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: @.&gt;; 发送时间: 2021年8月20日(星期五) 下午3:15 收件人: @.&gt;; 抄送: @.&gt;; @.&gt;; 主题: Re: [hengliusky/UltraSound_SSSR] ValueError: the number of data points must exceed order + 2 for Bayesian estimate the covariance matrix (#2) 我把数据集换成jpg格式得到刚刚的错误，换回png格式的话是直接读不到数据 ValueError: invalid PNG header … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: @.&gt;; 发送时间: 2021年8月20日(星期五) 中午11:21 收件人: @.&gt;; 抄送: @.&gt;; @.&gt;; 主题: Re: [hengliusky/UltraSound_SSSR] ValueError: the number of data points must exceed order + 2 for Bayesian estimate the covariance matrix (#2) 作者你好，我出现的这个错误是数据集的问题吗 raise ValueError("the number of data points must exceed order + 2 " ValueError: the number of data points must exceed order + 2 for Bayesian estimate the covariance matrix 你好，我在训练时没有遇到这样的错误。我在训练的时候只要把待超分辨的’.png‘图片放入到config.py中’input_path'这个属性中设置的文件夹下，,然后输入命令就可以正常运行了。刚刚我又重新测试了下，这样是可以正确运行的。 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. 'ValueError: invalid PNG header'，出现这个错误可能是PNG格式图片通过jpg格式图片直接修改后缀得来的。还有，你的训练环境可能和我的不一样。我的训练环境是：pytorch1.5.0， python3.8.3， matplotlib3.2.2， 你参考下。 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.
  
你在matlab中，运行下面代码：
 `clear;close all;
 
folder = './';
 scale = 4;
 
%% generate data
 filepaths = dir(fullfile(folder,'*.jpg'));
 for i = 1 : length(filepaths)
 image = imread(fullfile(folder,filepaths(i).name));
 im_label = modcrop(image, scale);
 im_lr= imresize(im_label, 1/scale, 'bicubic');
 imwrite(im_lr, ['./lr/', num2str(i), '.png'])
 imwrite(im_label,['./label/', num2str(i), '.png']);
 end
 
function imgs = modcrop(imgs, modulo)
 if size(imgs,3)==1
 sz = size(imgs);
 sz = sz - mod(sz, modulo);
 imgs = imgs(1:sz(1), 1:sz(2));
 else
 tmpsz = size(imgs);
 sz = tmpsz(1:2);
 sz = sz - mod(sz, modulo);
 imgs = imgs(1:sz(1), 1:sz(2),:);
 end
 end`
 这个代码就能得到lr图片和对应的hr图片，格式都是PNG的，可以直接用训练。运行的时候确保路径是正确的。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by hidonsea** [comment]
> 作者你好，PSNR和SSIM的计算是要自己引入的吗？
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "hengliusky/UltraSound_SSSR" ***@***.***&gt;; 发送时间:&nbsp;2021年8月21日(星期六) 中午11:54 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [hengliusky/UltraSound_SSSR] ValueError: the number of data points must exceed order + 2 for Bayesian estimate the covariance matrix (#2) 论文中所给的数据集下载下来就是jpg格式的，如果不用通过改后缀名的方式得到png格式，那请问作者你是怎么转换为png格式的呢 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: @.&gt;; 发送时间: 2021年8月20日(星期五) 下午3:15 收件人: @.&gt;; 抄送: @.&gt;; @.&gt;; 主题: Re: [hengliusky/UltraSound_SSSR] ValueError: the number of data points must exceed order + 2 for Bayesian estimate the covariance matrix (#2) 我把数据集换成jpg格式得到刚刚的错误，换回png格式的话是直接读不到数据 ValueError: invalid PNG header … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: @.&gt;; 发送时间: 2021年8月20日(星期五) 中午11:21 收件人: @.&gt;; 抄送: @.&gt;; @.&gt;; 主题: Re: [hengliusky/UltraSound_SSSR] ValueError: the number of data points must exceed order + 2 for Bayesian estimate the covariance matrix (#2) 作者你好，我出现的这个错误是数据集的问题吗 raise ValueError("the number of data points must exceed order + 2 " ValueError: the number of data points must exceed order + 2 for Bayesian estimate the covariance matrix 你好，我在训练时没有遇到这样的错误。我在训练的时候只要把待超分辨的’.png‘图片放入到config.py中’input_path'这个属性中设置的文件夹下，,然后输入命令就可以正常运行了。刚刚我又重新测试了下，这样是可以正确运行的。 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. 'ValueError: invalid PNG header'，出现这个错误可能是PNG格式图片通过jpg格式图片直接修改后缀得来的。还有，你的训练环境可能和我的不一样。我的训练环境是：pytorch1.5.0， python3.8.3， matplotlib3.2.2， 你参考下。 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. 你在matlab中，运行下面代码： `clear;close all; folder = './'; scale = 4; %% generate data filepaths = dir(fullfile(folder,'*.jpg')); for i = 1 : length(filepaths) image = imread(fullfile(folder,filepaths(i).name)); im_label = modcrop(image, scale); im_lr= imresize(im_label, 1/scale, 'bicubic'); imwrite(im_lr, ['./lr/', num2str(i), '.png']) imwrite(im_label,['./label/', num2str(i), '.png']); end function imgs = modcrop(imgs, modulo) if size(imgs,3)==1 sz = size(imgs); sz = sz - mod(sz, modulo); imgs = imgs(1:sz(1), 1:sz(2)); else tmpsz = size(imgs); sz = tmpsz(1:2); sz = sz - mod(sz, modulo); imgs = imgs(1:sz(1), 1:sz(2),:); end end` 这个代码就能得到lr图片和对应的hr图片，格式都是PNG的，可以直接用训练。运行的时候确保路径是正确的。 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

关于PSNR和SSIM的计算你可以参考下网上一些相关的帖子，他们讲的很清楚。US-CASE数据集是从我论文中给出的网站上随机选取的一些，你随机选取就行。
