### ISSUE TITLE
Training Strategy of this repository

### ISSUE THREAD

**Issue by albertchristianto** [hengliusky/UltraSound_SSSR#3]
Hi, what an interesting project.
I have a question regarding your training strategy.  Do you train a Cycle-GAN network for 1 specific image? Or Do you train a general Cycle-GAN network for all the training images?
best regards,
Albert Christianto

**Comment by hidonsea** [comment]
Thanks for attention. We train a network for a specific image.

**Comment by hidonsea** [comment]
> Hi, what an interesting project. I have a question regarding your training strategy. Do you train a Cycle-GAN network for 1 specific image? Or Do you train a general Cycle-GAN network for all the training images? best regards, Albert Christianto

Thanks for attention. We train a network for specific image.
